name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        architecture: 'x86'
    - name: unittests
      run:
        python3.6 -m venv .venv
        source .venv/bin/activate
        pip3 install -r requirements.txt
        ./skiddie.sh
        
