name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Schedule to run at 00:00 UTC on the 1st of every month
    - cron: '0 0 1 * *'

jobs:
  c-format:
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Clang-Format
      run: sudo apt-get install -y clang-format

    - name: Run Clang-Format
      run: |
        find . -name '*.c' -o -name '*.h' | xargs clang-format -style=file -i

    - name: Check for changes
      run: |
        git diff
        if [ -n "$(git diff)" ]; then
          echo "Code format issues found"
          exit 1
        fi

  python-format:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6"]  
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.python-version }}
  
    - name: Install dependencies
      run: |
        pip install black

    - name: Run Black
      run: |
        black --check .
